feature/CD-43
ekaripov/contacts-db pull request #15
Opened 2021-02-11 20:12 UTC by ekaripov

CD-43

2021-02-11 20:41 UTC, dshishkaryan requested changes

2021-02-11 20:41 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +    @GetMapping("")
Можно не ставить скобки с кавычками

2021-02-11 20:41 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +        if (contactTypeOptional.isPresent())
Что бы иф не писать у опшинал есть метод orelse кажется можно это в одну строчку записать

2021-02-11 20:41 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +        return ResponseEntity.ok(converter.convertToDto(contactTypeService.addContactType(contactType)));
У тебя тут в одну строчку а в первом методе в 3 с заданием переменных. Лучше наверное придерживаться одного стиля. Либо выносить в переменные либо сокращать строчки

2021-02-11 20:41 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +        return new ResponseEntity<Void>(HttpStatus.OK);
Ты в предыдущем методе используешь билдер а тут через new. Лучше как в предыдущем методе

2021-02-11 20:41 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +package ru.ekaripov.contactsdb.api.v1;
А ещё предлагаю вам сразу писать юнит и интеграционные тесты. Юнит тесты на сервисы. Интеграционные тесты на контроллеры. Можно прям не все покрывать, но будет полезно. Для контроллеров создаются json файлы которые отправляются на контроллеры

2021-02-11 22:00 UTC, ekaripov commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +package ru.ekaripov.contactsdb.api.v1;
Поскольку в тестах я ничего не понимаю, дамаю надо сначала написать хоть какой-то скелет. Пока тестить тупо нечего, а писать из головы я такое не смогу, так как не знаю как.

2021-02-11 22:12 UTC, ekaripov commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +        if (contactTypeOptional.isPresent())
Не понял как это реализовать. Выносить ResponseEntity  в объект?

2021-02-12 06:31 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +        if (contactTypeOptional.isPresent())
вот так:
        return contactTypeService.getById(id)
                .map(contactType -> ResponseEntity.ok(converter.convertToDto(contactType)))
                .orElseGet(() -> ResponseEntity.notFound().build());
Хотя в голове мне казалось это будет более читаемо на самом деле не уверен что это читается лучше. Так что наверное лучше твой вариант оставить )

2021-02-12 06:42 UTC, dshishkaryan commented on src/main/java/ru/ekaripov/contactsdb/api/v1/ContactTypeRestController.java
> +        if (contactTypeOptional.isPresent())
Плюс тут стрим используется. Но как вариант имей ввиду)

2021-02-15 20:38 UTC, merged